version: '3.9'

services:
  web:
    build: .
    container_name: paperapp
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./src:/app
    env_file:
      - .env
  db:
    image: postgres:15.3
    container_name: paperdb
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: paperdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"